language: node_js
cache: yarn
node_js:
- node
script:
- yarn upgrade ebnf2railroad
- yarn build
branches:
  only:
  - website
os: linux
dist: xenial
deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  keep_history: false
  local-dir: dist
  on:
    branch: website
env:
  gobal:
    secure: mzF97M3VJcO1aLqd3HParVd0etaBd7+1Eyc8BNVFAWInq3QXmHifRovgZpj0SySTj8B05Gne1r3dXNrbqkOI0UfJ6lbcdiz4tWwE3eotWnaQt7v/sFuKthPezP0+w5owqelUN/IzOlE25UhKMvpKwllZiiGjlLmUDkN93py3KzQLMWs12m/n6ZsnQLe21xWRuMzCzCXyaaqDivUFjEkrgn5RkcxTYWOjQDIsow2S7icCel9snS+iMTHMgVFUFdV6g3rqHEa3RS5jqY0Y5DkK+3H7ShVJsIqgWDnVcqQeDOZm/RO/1S676djJKNmbfrF3U0luAB8zFBaPRXIPn86maWP5tIi94z2hGR7esKHqw+iMv7fy6iCjp5zmxFfmvbzaLu2vguNZpGZnrDA6wHDtKpYWJl1BREUp9q2hWRQ9v1Qf+AIZm8EBPJnjxIIQDtcVPX9umyvb7QarZDQd7+rTpecDXefjsQIzgON0mXXc7DFMekKfxh6TVsf/G1id8dTV1vta1hIzFklf2dV6TZwJl9KBC2Dzyi39lafB4+CokubRS30wOMqN/LaNL5raIj1wUXEOF4yK8epw2bUPRqzscEDEysqVceluwEXDlxNydwpFhxE63DfBpNAGmF5WJbQNeSrHTbWTaozU6BAuVHptCgNxOpdzIUeGtH/H+aFIyws=
